#!/bin/bash
# Write a bash script that displays the information of dns
# shellcheck disable=SC2086
function display_dns_info {
    local domain=$1
    local subdomain=$2
    
    dig $subdomain.$domain | awk 'c&&!--c;/;; ANSWER SECTION:/{c=1}' | awk -v subdomain=$subdomain '{print "The subdomain " subdomain " is a " $4 " record and points to " $5 }'
    
    return 0
}

subdomains=("www" "lb-01" "web-01" "web-02")

if [[ $# -eq 1 ]]; then
    for subdomain in "${subdomains[@]}"; do
        display_dns_info $1 $subdomain
    done
elif [[ $# -eq 2 ]]; then
    display_dns_info $1 $2
else
    echo "Usage: $0 domain [subdomain]"
fi

