#!/usr/bin/env bash
# Configure Nginx server to point to another page
sudo apt-get install -y nginx
newsite="localhost;\n\tlocation \/redirect_me{\n\t\treturn 301 http:\/\/www.google.com;}"
sed -i "s/localhost;/$newsite/" /etc/nginx/sites-available/default
sudo service nginx restart
