#!/usr/bin/env bash
# Loadbalancer
if ! command -v haproxy &> /dev/null
then
	sudo apt-get update;
	sudo apt-get -y install haproxy;
fi
path="
frontend firstbalance\n\t
    bind *:80\n\t
    mode http\n\t
    option forwardfor\n\t
    default_backend webservers\n\n
backend webservers\n\t
    balance roundrobin\n\t
    63215-web-01 54.157.174.94\n\t
    63215-web-02 100.25.22.146\n\t
"
echo -e "$path" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
