#!/usr/bin/env bash
# You add condition in your loop


a=1
b=4
c=8
d=10


while [ $a -le $d ];
do
	echo "Best School";

	if [ "$a" -eq "$b" ]; then
		echo "bad luck"
	elif [ "$a" -eq "$c" ]; then
		echo "good luck"
	fi
	((a++))
done
